# Generated by Django 5.0 on 2024-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPSAMPLE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='count_views',
        ),
    ]
