# Generated by Django 5.0.4 on 2024-04-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPSAMPLE', '0004_comment_alter_contact_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-create_date']},
        ),
    ]
