# Generated by Django 5.0 on 2024-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_create_date_post_publish_date_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
