# Generated by Django 5.0 on 2024-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_count_views_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
    ]
