# Generated by Django 5.0 on 2024-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images.jpg', upload_to='blog/'),
        ),
    ]
