# Generated by Django 5.0.4 on 2024-04-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
