# Generated by Django 5.0.4 on 2024-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
    ]
