# Generated by Django 5.0.4 on 2024-05-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
